// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrUpdateJob = `-- name: CreateOrUpdateJob :one
INSERT INTO jobs (id, type, name, description, schedule, last_run_time, next_run_time, payload, status, shard_id) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, description, type, schedule, last_run_time, next_run_time, payload, status, shard_id, inserted_at, updated_at
`

type CreateOrUpdateJobParams struct {
	ID          uuid.UUID          `json:"id"`
	Type        string             `json:"type"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Schedule    string             `json:"schedule"`
	LastRunTime pgtype.Timestamptz `json:"last_run_time"`
	NextRunTime pgtype.Timestamptz `json:"next_run_time"`
	Payload     []byte             `json:"payload"`
	Status      pgtype.Text        `json:"status"`
	ShardID     pgtype.Int4        `json:"shard_id"`
}

func (q *Queries) CreateOrUpdateJob(ctx context.Context, arg CreateOrUpdateJobParams) (Jobs, error) {
	row := q.db.QueryRow(ctx, createOrUpdateJob,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.Schedule,
		arg.LastRunTime,
		arg.NextRunTime,
		arg.Payload,
		arg.Status,
		arg.ShardID,
	)
	var i Jobs
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Schedule,
		&i.LastRunTime,
		&i.NextRunTime,
		&i.Payload,
		&i.Status,
		&i.ShardID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, name, description, type, schedule, last_run_time, next_run_time, payload, status, shard_id, inserted_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Jobs, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Jobs
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Schedule,
		&i.LastRunTime,
		&i.NextRunTime,
		&i.Payload,
		&i.Status,
		&i.ShardID,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, name, description, type, schedule, last_run_time, next_run_time, payload, status, shard_id, inserted_at, updated_at FROM jobs 
ORDER BY id 
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Jobs, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Jobs{}
	for rows.Next() {
		var i Jobs
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Schedule,
			&i.LastRunTime,
			&i.NextRunTime,
			&i.Payload,
			&i.Status,
			&i.ShardID,
			&i.InsertedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobNextRunTimeAndStatus = `-- name: UpdateJobNextRunTimeAndStatus :exec
UPDATE jobs 
SET next_run_time = $2, 
    payload = $3, 
    status = $4 
WHERE id = $1
`

type UpdateJobNextRunTimeAndStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	NextRunTime pgtype.Timestamptz `json:"next_run_time"`
	Payload     []byte             `json:"payload"`
	Status      pgtype.Text        `json:"status"`
}

func (q *Queries) UpdateJobNextRunTimeAndStatus(ctx context.Context, arg UpdateJobNextRunTimeAndStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobNextRunTimeAndStatus,
		arg.ID,
		arg.NextRunTime,
		arg.Payload,
		arg.Status,
	)
	return err
}
