// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Jobs struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Type        string             `json:"type"`
	Schedule    string             `json:"schedule"`
	LastRunTime pgtype.Timestamptz `json:"last_run_time"`
	NextRunTime pgtype.Timestamptz `json:"next_run_time"`
	Payload     []byte             `json:"payload"`
	Status      pgtype.Text        `json:"status"`
	ShardID     pgtype.Int4        `json:"shard_id"`
	InsertedAt  pgtype.Timestamptz `json:"inserted_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
