// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrUpdateJob(ctx context.Context, arg CreateOrUpdateJobParams) (Jobs, error)
	DeleteJob(ctx context.Context, id uuid.UUID) error
	GetJob(ctx context.Context, id uuid.UUID) (Jobs, error)
	UpdateJobNextRunTimeAndStatus(ctx context.Context, arg UpdateJobNextRunTimeAndStatusParams) error
}

var _ Querier = (*Queries)(nil)
