// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrUpdateJob(ctx context.Context, arg CreateOrUpdateJobParams) (Jobs, error)
	DeleteJob(ctx context.Context, id uuid.UUID) error
	GetJob(ctx context.Context, id uuid.UUID) (Jobs, error)
	GetNext24HourJobs(ctx context.Context) ([]Jobs, error)
	GetNextHourJobs(ctx context.Context) ([]Jobs, error)
	GetNextMinuteJobs(ctx context.Context) ([]Jobs, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Jobs, error)
	UpdateJobCompletedAt(ctx context.Context, arg UpdateJobCompletedAtParams) error
	UpdateJobShardIs(ctx context.Context, arg UpdateJobShardIsParams) error
	UpdateJobStartedAt(ctx context.Context, arg UpdateJobStartedAtParams) error
}

var _ Querier = (*Queries)(nil)
